#ASP.Net Core

trigger:
  - master

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(builConfiguration)'
